routes/web.php
    if (file_exists($file_path))
    {
        return Response::download($file_path);
    }
    else
    {
        exit('Файла не существует.');
    }
});

Route::get('{dashbord}/download/{folder}/{filename}', function($dashbord, $folder, $filename)
{

    $file_path = storage_path()."/app/public/".$folder."/".$filename;
    //exit($file_path);
    if (file_exists($file_path))
    {
        return Response::download($file_path);
    }
    else
    {
        exit('Файла не существует.');
    }
});

//Cabinet

Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'Cabinet',
        'middleware' => ['auth'],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');

        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
            Route::get('/', 'ProfileController@index')->name('home');
            Route::get('/edit', 'ProfileController@edit')->name('edit');
            Route::put('/update', 'ProfileController@update')->name('update');
        });
    }
);

//Admin

Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'namespace' => 'Admin',
        'middleware' => ['auth'],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::post('/history', 'HomeController@createRecord')->name('history');
        Route::resource('users', 'UsersController');
        Route::get('/sales', 'UsersController@sales')->name('users.sales');
        Route::get('/purchase', 'UsersController@purchase')->name('users.purchase');
        Route::get('/logist', 'UsersController@logist')->name('users.logist');
        Route::get('/accountant', 'UsersController@accountant')->name('users.accountant');
        Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');
    }
);

//Accountant

Route::group(
    [
        'prefix' => 'accountant',
        'as' => 'accountant.',
        'namespace' => 'Accountant',
        'middleware' => ['auth', 'accountant'],
    ],
    function () {
        Route::get('/order', 'HomeController@order')->name('order.index');
        Route::post('/order/num', 'HomeController@orderNumber')->name('order.num');

        Route::get('/arrival', 'HomeController@arrival')->name('arrival.index');
        Route::post('/arrival/check', 'HomeController@checkArrival')->name('arrival.check');

        Route::get('/loading', 'HomeController@loading')->name('loading.index');
        Route::post('/loading/file', 'HomeController@loadFiles')->name('loading.file');

        Route::get('/archive', 'HomeController@archive')->name('archive.index');

        Route::post('/print', 'HomeController@print')->name('print');
    }
);

//Logist

Route::group(
    [
        'prefix' => 'logist',
        'as' => 'logist.',
        'namespace' => 'Logist',
        'middleware' => ['auth', 'logist'],
    ],
    function () {
        Route::group(
            [
                'prefix' => 'not_registry',
                'as' => 'not_registry.',
            ],
            function () {
                Route::group(
                    [
                        'prefix' => 'new',
                        'as' => 'new.',
                    ],
                    function () {
                        Route::get('/sale', 'NotRegistryLogistController@index')->name('sale');
                        Route::get('/purchase', 'NotRegistryLogistController@purchase')->name('purchase');
                        Route::get('/sale_logist', 'NotRegistryLogistForSaleController@index')->name('sale_logist');
                    }
                );
                Route::group(
                    [
                        'prefix' => 'sale',
                        'as' => 'sale.',
                    ],
                    function () {
                        Route::post('/print', 'NotRegistryLogistController@printSale')->name('print');
                    }
                );

                Route::group(
                    [
                        'prefix' => 'purchase',
                        'as' => 'purchase.',
                    ],
                    function () {
                        Route::post('/answer', 'NotRegistryLogistController@giveAnswer')->name('new.answer');
                        Route::match(['get', 'post'], '/request_car', 'NotRegistryLogistController@requestCar')->name('request_car.index');
                        Route::get('/request_car/take/{id_request}/{id_req_accept}', 'NotRegistryLogistController@startSearchCar')->name('request_car.take');
                        Route::post('/request_car/other', 'NotRegistryLogistController@other')->name('request_car.other');

                        Route::match(['get', 'post'], '/search', 'NotRegistryLogistController@search')->name('search.index');
                        Route::post('/search/driver', 'NotRegistryLogistController@findCar')->name('search.driver');

                        Route::match(['get', 'post'], '/delivery', 'NotRegistryLogistController@delivery')->name('delivery.index');
                        Route::post('/delivery/file', 'NotRegistryLogistController@loadFiles')->name('delivery.file');

                        Route::match(['get', 'post'], '/check_delivery', 'NotRegistryLogistController@checkDelivery')->name('check_delivery.index');
                        Route::post('/check_delivery/file', 'NotRegistryLogistController@checkDeliveryFiles')->name('check_delivery.file');

                        Route::match(['get', 'post'], '/payment', 'NotRegistryLogistController@payment')->name('payment.index');
                        Route::get('/payment/do/{id_request}/{id_req_accept}', 'NotRegistryLogistController@getPayment')->name('payment.do');

                        Route::match(['get', 'post'], '/archive_complete', 'NotRegistryLogistController@archiveComplete')->name('archive_complete.index');
                        Route::match(['get', 'post'], '/problem_request', 'NotRegistryLogistController@problemRequest')->name('problem_request.index');

                        Route::post('/print', 'NotRegistryLogistController@printPurchase')->name('print');
                    }
                );

                Route::group(
                    [
                        'prefix' => 'sale_logist',
                        'as' => 'sale_logist.',
                    ],
                    function () {
                        Route::post('/answer', 'NotRegistryLogistForSaleController@giveAnswer')->name('new.answer');
                        Route::match(['get', 'post'], '/request_car', 'NotRegistryLogistForSaleController@requestCar')->name('request_car.index');
                        Route::get('/request_car/take/{id_request}/{id_req_accept}', 'NotRegistryLogistForSaleController@startSearchCar')->name('request_car.take');
                        Route::post('/request_car/other', 'NotRegistryLogistForSaleController@other')->name('request_car.other');

                        Route::match(['get', 'post'], '/search', 'NotRegistryLogistForSaleController@search')->name('search.index');
                        Route::post('/search/driver', 'NotRegistryLogistForSaleController@findCar')->name('search.driver');

                        Route::match(['get', 'post'], '/delivery', 'NotRegistryLogistForSaleController@delivery')->name('delivery.index');
                        Route::post('/delivery/file', 'NotRegistryLogistForSaleController@loadFiles')->name('delivery.file');

                        Route::match(['get', 'post'], '/check_delivery', 'NotRegistryLogistForSaleController@checkDelivery')->name('check_delivery.index');
                        Route::post('/check_delivery/file', 'NotRegistryLogistForSaleController@checkDeliveryFiles')->name('check_delivery.file');

                        Route::match(['get', 'post'], '/payment', 'NotRegistryLogistForSaleController@payment')->name('payment.index');
                        Route::get('/payment/do/{id_request}/{id_req_accept}', 'NotRegistryLogistForSaleController@getPayment')->name('payment.do');

                        Route::match(['get', 'post'], '/archive_complete', 'NotRegistryLogistForSaleController@archiveComplete')->name('archive_complete.index');
                        Route::match(['get', 'post'], '/problem_request', 'NotRegistryLogistForSaleController@problemRequest')->name('problem_request.index');

                        Route::post('/print', 'NotRegistryLogistForSaleController@print')->name('print');
                    }
                );


                Route::group(
                    [
                        'prefix' => 'archive',
                        'as' => 'archive.',
                    ],
                    function () {
                        Route::match(['get', 'post'], '/sale', 'NotRegistryLogistController@archive')->name('sale');
                        Route::match(['get', 'post'], '/purchase', 'NotRegistryLogistController@archivePurchase')->name('purchase');
                        Route::get('/sale_logist', 'NotRegistryLogistForSaleController@archive')->name('sale_logist');
                    }
                );

            }
        );
        Route::group(
            [
                'prefix' => 'statistic',
                'as' => 'statistic.',
            ],
            function () {
                Route::match(['get', 'post'],'/index', 'StatisticLogistController@index')->name('index');
            }
        );
    }
);

//Sale Logist

Route::group(
    [
        'prefix' => 'sale_logist',
        'as' => 'sale_logist.',
        'namespace' => 'SaleLogist',
        'middleware' => ['auth', 'sale_logist'],
    ],
    function () {
        Route::group(
            [
                'prefix' => 'not_registry',
                'as' => 'not_registry.',
            ],
            function () {

resources/views/sale/not_registry/archive_answer/_nav.blade.php
<ul class="nav nav-tabs mb-3">
    <li class="nav-item"><a class="nav-link" href="{{ route('sale.not_registry.new.index') }}">Запросы на расчет</a></li>
    <li class="nav-item"><a class="nav-link" href="{{ route('sale.not_registry.answer.index') }}">Ответы на запросы</a></li>
    <li class="nav-item"><a class="nav-link active" href="{{ route('sale.not_registry.archive_answer.index') }}">Архив запросов</a></li>
    <li class="nav-item"><a class="nav-link" href="{{ route('sale.not_registry.archive_price.index') }}">Архив готовых цен</a></li>
    <li class="nav-item"><a class="nav-link" href="{{ route('sale.not_registry.requests.index') }}">Запросы в пути</a></li>
</ul>

resources/views/sale/not_registry/archive_answer/index.blade.php
@extends('layouts.app', ['navigator' => 'Отдел продаж'])
@section('menu')
    @include('sale.not_registry._vertical_nav')
@endsection
@section('content')
    @include('sale.not_registry.archive_answer._nav')
    @include('sale.not_registry.search',['type_load' => $type_load])

    @if (!$search)
        <div class="col-md-1">
            <form id="print" method="POST" action="{{ route('sale.not_registry.print') }}" target="_blank">
                @csrf
                <input type="hidden"  id="page" name="page" value="archive_answer">
                <h2><span style="cursor: pointer;" onclick="$('#print').submit();" data-toggle='tooltip' title='Вывести на печать'>&#128424;</span></h2>
            </form>
        </div>
    @endif

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>№</th>
            <th>Дата</th>
            <th>Менеджер</th>
            <th>Комментарий</th>
            <th>Точка А</th>
            <th>Точка Б</th>
            <th>Расстояние</th>
            <th>Тоннаж(кг)</th>
            <th>Тип загрузки</th>
            @if ($search && $status)
                <th>Статус</th>
                @php($status_sale = [1=>'Запросы на расчет', 2=>'Ответы на запросы', 3=>'Архив запросов', 4=>'Архив готовых цен'])
            @else
                <th style="background: #c1e2b3;">Цена</th>
                <th style="background: #c1e2b3;">Комментарий</th>
                <th style="background: #c1e2b3;">Дата ответа</th>
                <th style="background: #c1e2b3;">Логист</th>
            @endif
        </tr>
        </thead>
        <tbody>

        @foreach ($requests as $req)
            <tr>
                <td>{{ $req->id }}</td>
               <td>{{ date("d.m.y H:i:s", strtotime($req->created_at)) }}</td>
                <td>{{ $req->userCreate->name }}</td>
                <td>{{ $req->comment_create }}</td>

                <td>{{ $req->farmsAddressA->name }}, {{ $req->farmsAddressA->address }}</td>
                <td>{{ $req->farmsAddressB->name }}, {{ $req->farmsAddressB->address }}</td>
                <td>{{ $req->distance }}</td>
                <td>{{ $req->tonnage }}</td>
                <td>{{ $req->typeLoad->name }}</td>
                @if ($search && $status)
                    <td>{{ $status_sale[$req->id_status_sale] }}</td>
                @else
                    <td style="background: #c1e2b3;">{{ $req->price }}</td>
                    <td style="background: #c1e2b3;">{{ $req->comment }}</td>
                    <td style="background: #c1e2b3;">
                        @if (!empty($req->date_answer))
                            {{ date("d.m.y H:i:s", strtotime($req->date_answer)) }}
                        @endif
                    </td>
                    <td style="background: #c1e2b3;">
                        @if (isset($req->userLogist))
                            @if (!empty($req->userLogist->last_name))
                                {{$req->userLogist->last_name }},
                            @endif
                            {{$req->userLogist->name}}
                        @endif
                    </td>
                @endif
            </tr>
        @endforeach

        </tbody>
    </table>
    @if ($requests instanceof \Illuminate\Pagination\AbstractPaginator)
        {{ $requests->links() }}
    @endif
@endsection