routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('home')->middleware(['auth', 'role']);

Route::get('/home', 'HomeController@notRole')->name('no_role')->middleware(['auth']);

Auth::routes();

Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');

Route::post('/help', 'HomeController@help')->name('help');

// Download Route

Route::get('{dashbord}/{category}/{subcategory}/download/{folder}/{filename}', function($dashbord, $category, $subcategory, $folder, $filename)
{

    $file_path = storage_path()."/app/public/".$folder."/".$filename;
    //exit($file_path);
    if (file_exists($file_path))
    {
        return Response::download($file_path);
    }
    else
    {
        exit('Файла не существует.');
    }
});

Route::get('{dashbord}/{category}/download/{folder}/{filename}', function($dashbord, $category, $folder, $filename)
{

    $file_path = storage_path()."/app/public/".$folder."/".$filename;
    //exit($file_path);
    if (file_exists($file_path))
    {
        return Response::download($file_path);
    }
    else
    {
        exit('Файла не существует.');
    }
});

Route::get('{dashbord}/download/{folder}/{filename}', function($dashbord, $folder, $filename)
{

    $file_path = storage_path()."/app/public/".$folder."/".$filename;
    //exit($file_path);
    if (file_exists($file_path))
    {
        return Response::download($file_path);
    }
    else
    {
        exit('Файла не существует.');
    }
});

//Cabinet

Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'Cabinet',
        'middleware' => ['auth'],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');

        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
            Route::get('/', 'ProfileController@index')->name('home');
            Route::get('/edit', 'ProfileController@edit')->name('edit');
            Route::put('/update', 'ProfileController@update')->name('update');
        });
    }
);

//Admin

Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'namespace' => 'Admin',
        'middleware' => ['auth'],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::post('/history', 'HomeController@createRecord')->name('history');
        Route::resource('users', 'UsersController');
        Route::get('/sales', 'UsersController@sales')->name('users.sales');
        Route::get('/purchase', 'UsersController@purchase')->name('users.purchase');
        Route::get('/logist', 'UsersController@logist')->name('users.logist');
        Route::get('/accountant', 'UsersController@accountant')->name('users.accountant');
        Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');
    }
);

//Accountant

Route::group(
    [
        'prefix' => 'accountant',
        'as' => 'accountant.',
        'namespace' => 'Accountant',
        'middleware' => ['auth', 'accountant'],
    ],
    function () {
        Route::get('/order', 'HomeController@order')->name('order.index');
        Route::post('/order/num', 'HomeController@orderNumber')->name('order.num');

        Route::get('/arrival', 'HomeController@arrival')->name('arrival.index');
        Route::post('/arrival/check', 'HomeController@checkArrival')->name('arrival.check');

        Route::get('/loading', 'HomeController@loading')->name('loading.index');
        Route::post('/loading/file', 'HomeController@loadFiles')->name('loading.file');

        Route::get('/archive', 'HomeController@archive')->name('archive.index');

        Route::post('/print', 'HomeController@print')->name('print');
    }
);

//Logist

Route::group(
    [
        'prefix' => 'logist',
        'as' => 'logist.',
        'namespace' => 'Logist',
        'middleware' => ['auth', 'logist'],
    ],
    function () {
        Route::group(
            [
                'prefix' => 'not_registry',
                'as' => 'not_registry.',
            ],
            function () {
                Route::group(
                    [
                        'prefix' => 'new',
                        'as' => 'new.',
                    ],
                    function () {
                        Route::get('/sale', 'NotRegistryLogistController@index')->name('sale');
                        Route::get('/purchase', 'NotRegistryLogistController@purchase')->name('purchase');
                        Route::get('/sale_logist', 'NotRegistryLogistForSaleController@index')->name('sale_logist');
                    }
                );
                Route::group(
                    [
                        'prefix' => 'sale',
                        'as' => 'sale.',
                    ],
                    function () {
                        Route::post('/print', 'NotRegistryLogistController@printSale')->name('print');
                    }
                );

                Route::group(
                    [
                        'prefix' => 'purchase',
                        'as' => 'purchase.',
                    ],
                    function () {
                        Route::post('/answer', 'NotRegistryLogistController@giveAnswer')->name('new.answer');
                        Route::match(['get', 'post'], '/request_car', 'NotRegistryLogistController@requestCar')->name('request_car.index');
                        Route::get('/request_car/take/{id_request}/{id_req_accept}', 'NotRegistryLogistController@startSearchCar')->name('request_car.take');
                        Route::post('/request_car/other', 'NotRegistryLogistController@other')->name('request_car.other');

                        Route::match(['get', 'post'], '/search', 'NotRegistryLogistController@search')->name('search.index');
                        Route::post('/search/driver', 'NotRegistryLogistController@findCar')->name('search.driver');

                        Route::match(['get', 'post'], '/delivery', 'NotRegistryLogistController@delivery')->name('delivery.index');
                        Route::post('/delivery/file', 'NotRegistryLogistController@loadFiles')->name('delivery.file');

                        Route::match(['get', 'post'], '/check_delivery', 'NotRegistryLogistController@checkDelivery')->name('check_delivery.index');
                        Route::post('/check_delivery/file', 'NotRegistryLogistController@checkDeliveryFiles')->name('check_delivery.file');

                        Route::match(['get', 'post'], '/payment', 'NotRegistryLogistController@payment')->name('payment.index');
                        Route::get('/payment/do/{id_request}/{id_req_accept}', 'NotRegistryLogistController@getPayment')->name('payment.do');

                        Route::match(['get', 'post'], '/archive_complete', 'NotRegistryLogistController@archiveComplete')->name('archive_complete.index');
                        Route::match(['get', 'post'], '/problem_request', 'NotRegistryLogistController@problemRequest')->name('problem_request.index');

                        Route::post('/print', 'NotRegistryLogistController@printPurchase')->name('print');
                    }
                );

                Route::group(
                    [
                        'prefix' => 'sale_logist',
                        'as' => 'sale_logist.',
                    ],
                    function () {
                        Route::post('/answer', 'NotRegistryLogistForSaleController@giveAnswer')->name('new.answer');
                        Route::match(['get', 'post'], '/request_car', 'NotRegistryLogistForSaleController@requestCar')->name('request_car.index');
                        Route::get('/request_car/take/{id_request}/{id_req_accept}', 'NotRegistryLogistForSaleController@startSearchCar')->name('request_car.take');
                        Route::post('/request_car/other', 'NotRegistryLogistForSaleController@other')->name('request_car.other');

                        Route::match(['get', 'post'], '/search', 'NotRegistryLogistForSaleController@search')->name('search.index');
                        Route::post('/search/driver', 'NotRegistryLogistForSaleController@findCar')->name('search.driver');

                        Route::match(['get', 'post'], '/delivery', 'NotRegistryLogistForSaleController@delivery')->name('delivery.index');
                        Route::post('/delivery/file', 'NotRegistryLogistForSaleController@loadFiles')->name('delivery.file');

                        Route::match(['get', 'post'], '/check_delivery', 'NotRegistryLogistForSaleController@checkDelivery')->name('check_delivery.index');
                        Route::post('/check_delivery/file', 'NotRegistryLogistForSaleController@checkDeliveryFiles')->name('check_delivery.file');

                        Route::match(['get', 'post'], '/payment', 'NotRegistryLogistForSaleController@payment')->name('payment.index');
                        Route::get('/payment/do/{id_request}/{id_req_accept}', 'NotRegistryLogistForSaleController@getPayment')->name('payment.do');

                        Route::match(['get', 'post'], '/archive_complete', 'NotRegistryLogistForSaleController@archiveComplete')->name('archive_complete.index');
                        Route::match(['get', 'post'], '/problem_request', 'NotRegistryLogistForSaleController@problemRequest')->name('problem_request.index');

                        Route::post('/print', 'NotRegistryLogistForSaleController@print')->name('print');
                    }
                );


                Route::group(
                    [
                        'prefix' => 'archive',
                        'as' => 'archive.',
                    ],
                    function () {
                        Route::match(['get', 'post'], '/sale', 'NotRegistryLogistController@archive')->name('sale');

app/Http/Controllers/Logist/StatisticLogistController.php
<?php

namespace app\Http\Controllers\Logist;


use app\Entity\RequestPurchase;
use Illuminate\Http\Request;
use app\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class StatisticLogistController extends Controller
{
    public function index(Request $request)
    {
        if ($request->isMethod('post')) {
            $datefilter = $request->get('daterange');
            $from = substr($datefilter, 0, 10);
            $to = substr($datefilter, 13, 10);

            $requests = RequestPurchase::select('id_request_accept','date_export', 'id_shipping', 'id_status_logist')->whereIn('id_status_logist', [RequestPurchase::LPAYMENT, RequestPurchase::LARCHIVE_COMPLETE,
                RequestPurchase::LDELIVERY, RequestPurchase::LCHECK_DELIVERY])
                ->whereBetween('date_export', [date('Y-m-d',strtotime($from)), date('Y-m-d', strtotime($to))])
                ->with(['requestPurchaseAccepted'])->get();
            $counts = [];
            //return $requests;
            //$counts['in'] = [];

            foreach ($requests as $req) {
                $type = 'in';
                if ($req->id_shipping == 3) {
                    $type = 'out';
                }
                $date_m =[1=>'Январь', 2=>'Февраль', 3=>'Март', 4=>'Апрель', 5=>'Май', 6=>'Июнь', 7=>'Июль', 8=>'Август', 9=>'Сентябрь', 10=>'Октябрь', 11=>'Ноябрь', 12=>'Декабрь'];
                $date = $date_m[date('n', strtotime($req->date_export))]." ".date('Y', strtotime($req->date_export));
                //$date = date('Y-m', strtotime($req->date_export));

                if (!empty($counts[$date][$type]['all'])) {
                    $counts[$date][$type]['all'] += 1;
                }
                else {
                    $counts[$date][$type]['all'] = 1;
                }
                if ($req->id_status_logist == RequestPurchase::LPAYMENT || $req->id_status_logist == RequestPurchase::LARCHIVE_COMPLETE) {
                    if (!empty($counts[$date][$type]['fact'])) {
                        $counts[$date][$type]['fact'] += 1;
                    }
                    else {
                        $counts[$date][$type]['fact'] = 1;
                    }
                    if (strtotime($req->requestPurchaseAccepted->date_come_car_take) > strtotime($req->date_export)) {
                        if (!empty($counts[$date][$type]['late'])) {
                            $counts[$date][$type]['late'] += 1;
                        }
                        else {
                            $counts[$date][$type]['late'] = 1;
                        }
                    }
                    else {
                        if (!empty($counts[$date][$type]['ok'])) {
                            $counts[$date][$type]['ok'] += 1;
                        }
                        else {
                            $counts[$date][$type]['ok'] = 1;
                        }
                    }
                }
            }
            return $counts;
        }
        else {
            return view('logist.statistic.index');
        }
    }
}

resources/views/logist/not_registry/_vertical_nav.blade.php
<div class="nav nav-pills nav-fill flex-column">
    <li class="nav-item"><a class="nav-link active" href="{{ route('logist.not_registry.new.purchase') }}">НеРеестр</a></li>
    <li class="nav-item"><a class="nav-link" href="{{ route('logist.statistic.index') }}">Статистика</a></li>
</div>

resources/views/logist/not_registry/history.blade.php
@component('modal')
    @slot('name', 'history-modal')
    @slot('title', 'История цен')
    @slot('route', 'home')
    @slot('enctype', '')

        {!! csrf_field() !!}

    <div id="show_history"></div>


    @slot('buttons')
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
    @endslot
@endcomponent

resources/views/logist/not_registry/print_purchase.blade.php
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Print</title>
    <style type="text/css">
        table {
            width:100%;
            border: 1px solid black;
            border-collapse:collapse;
        }
        th {
            text-align: left; /* Выравнивание по левому краю */
            background: #D3D3D3; /* Цвет фона ячеек */
            border: 1px solid black; /* Граница вокруг ячеек */
        }
        td {
            border: 1px solid black; /* Граница вокруг ячеек */
        }
    </style>

</head>
<body onload="setTimeout(function () { window.print(); }, 500); window.onfocus = function () { setTimeout(function () { window.close(); }, 500); }">
<table>
    <thead>
    <tr>
        <th>№</th>
        <th>Дата</th>
        <th>Менеджер</th>
        <th>Комментарий</th>
        <th>Тип перевозки</th>
        <th>Точка А</th>
        <th>Точка Б</th>
        <th>Расстояние</th>
        <th>Тоннаж(кг)</th>
        <th>Тип загрузки</th>
        <th>Товары</th>
        <th>ADR</th>
        <th>Упаковка</th>
        <th>Дата вывоза</th>
        <th>Поддоны</th>
        @if ($type == "archive" || $type == "problem_request" || $type == "request_car" || $type == "search" || $type == "delivery" ||
            $type == "check_delivery" || $type == "payment" || $type == "archive_complete")
            <th>Цена</th>
            <th>Комментарий</th>
            <th>Дата ответа</th>
            <th>Логист</th>
        @endif
        @if ($type == "problem_request")
            <th>Причина попадания</th>
        @endif
        @if ($type == "request_car" || $type == "search" || $type == "delivery" || $type == "check_delivery" || $type == "payment" || $type == "archive_complete")
            <th>Дата запроса на перевозку</th>
            <th>Грузоотправитель</th>
            <th>Грузополучатель</th>
            <th>Менеджер</th>
            <th>№ заказа в 1С (поставщик)</th>
            <th>№ заказа в 1С (клиент)</th>
        @endif
        @if ($type == "search" || $type == "delivery" || $type == "check_delivery" || $type == "payment" || $type == "archive_complete")
            <th>Дата начала поиска машины</th>
        @endif
        @if ($type == "delivery" || $type == "check_delivery" || $type == "payment" || $type == "archive_complete")
            <th>№ в умной логистике</th>
            <th>Водитель</th>
            <th>Дата окончания поиска машины</th>
            <th>Дата ввода данных от зкакупки</th>
            <th>Дата прибытия к грузоотправителю</th>
            <th>Товары</th>
            <th>Дата ответа бухгалтерии</th>
            <th>Бухгалтер</th>
        @endif
        @if ($type == "check_delivery" || $type == "payment" || $type == "archive_complete")
            <th>Дата прибытия машины</th>
        @endif
        @if ($type == "archive_complete")
            <th>Дата перемещения в архив</th>
        @endif
    </tr>
    </thead>
    <tbody>

    @foreach ($requests as $req)
        <tr>
            <td>{{ $req->id }}</td>
            <td>{{ date("d.m.y H:i:s", strtotime($req->created_at)) }}</td>
            <td>{{ $req->userCreate->name }}</td>
            <td>{{ $req->comment_create }}</td>

            <td>{{ $req->shipping->name }}</td>
            <td>{{ $req->farmsAddressA->name }}, {{ $req->farmsAddressA->address }}</td>
            <td>{{ $req->farmsAddressB->name }}, {{ $req->farmsAddressB->address }}</td>
            <td>{{ $req->distance }}</td>
            <td>{{ $req->tonnage }}</td>
            <td>{{ $req->typeLoad->name }}</td>
            <td>
                @foreach($req->products as $prod)
                    {{ $prod->name }} <br>
                @endforeach
            </td>
            <td>{{ $req->adr }}</td>
            <td>{{ $req->packaging->name }}</td>
            <td>
                @if (!empty($req->date_export))
                    {{ date("d.m.y H:i:s", strtotime($req->date_export)) }}
                @endif
            </td>
            <td>
                @if ($req->pallet == 0)
                    Нет
                @else
                    Да
                @endif
            </td>
            @if ($type == "archive" || $type == "problem_request" || $type == "request_car" || $type == "search" || $type == "delivery" ||
            $type == "check_delivery" || $type == "payment" || $type == "archive_complete")
                <td>
                    {{ $req->price }}
                </td>
                <td>{{ $req->comment }}</td>
                <td>
                    @if (!empty($req->date_answer))
                        {{ date("d.m.y H:i:s", strtotime($req->date_answer)) }}
                    @endif
                </td>
                <td>
                    @if (isset($req->userLogist))
                        @if (!empty($req->userLogist->last_name))
                            {{$req->userLogist->last_name }},
                        @endif
                        {{$req->userLogist->name}}
                    @endif
                </td>
            @endif
            @if ($type == "problem_request")
                <td>{{ $req->comment_problem }}</td>
            @endif
            @if ($type == "request_car" || $type == "search" || $type == "delivery" || $type == "check_delivery" || $type == "payment" || $type == "archive_complete")
                <td>
                    @if (!empty($req->requestPurchaseAccepted['created_at']))
                        {{ date("d.m.y H:i:s", strtotime($req->requestPurchaseAccepted['created_at'])) }}
                    @endif
                </td>
                <td>{{ $req->requestPurchaseAccepted['contactShipper']['name'] }}<br>{{ $req->requestPurchaseAccepted['contactShipper']['phones'] }}<br><i>{{ $req->requestPurchaseAccepted['comment_shipper'] }}</i></td>
                <td>{{ $req->requestPurchaseAccepted['contactConsignee']['name'] }}<br>{{ $req->requestPurchaseAccepted['contactConsignee']['phones'] }}<br><i>{{ $req->requestPurchaseAccepted['comment_consignee'] }}</i></td>
                <td>{{ $req->requestPurchaseAccepted['name_manager'] }}</td>
                <td>{{ $req->requestPurchaseAccepted['num_provider'] }}</td>
                <td>{{ $req->requestPurchaseAccepted['num_customer'] }}</td>
            @endif
            @if ($type == "search" || $type == "delivery" || $type == "check_delivery" || $type == "payment" || $type == "archive_complete")
                <td>
                    @if (!empty($req->requestPurchaseAccepted['date_start_search']))
                        {{ date("d.m.y H:i:s", strtotime($req->requestPurchaseAccepted['date_start_search'])) }}
                    @endif
                </td>
            @endif
            @if ($type == "delivery" || $type == "check_delivery" || $type == "payment" || $type == "archive_complete")
                <td>
                    {{ $req->requestPurchaseAccepted['num_logistic'] }}
                </td>
                <td>{{ $req->requestPurchaseAccepted['car']['driver']['name'] }},<br>
                    @if (!empty($req->requestPurchaseAccepted['car']['driver']['birthday']))
                        {{ date("d.m.y", strtotime($req->requestPurchaseAccepted['car']['driver']['birthday'])) }},
                    @endif
                    @if (!empty($req->requestPurchaseAccepted['car']['driver']['series']))
                        Паспорт: {{$req->requestPurchaseAccepted['car']['driver']['series']}},
                        {{$req->requestPurchaseAccepted['car']['driver']['number']}},
                    @endif
                    @if (!empty($req->requestPurchaseAccepted['car']['driver']['whom']))
                        выдан: {{$req->requestPurchaseAccepted['car']['driver']['whom']}},
                        {{ date("d.m.y", strtotime($req->requestPurchaseAccepted['car']['driver']['when'])) }},
                    @endif
                    @if (!empty($req->requestPurchaseAccepted['car']['driver']['phone']))
                        #телефона: {{$req->requestPurchaseAccepted['car']['driver']['phone']}},
                    @endif
                    @if (!empty($req->requestPurchaseAccepted['car']['model']))
                        Машина: {{$req->requestPurchaseAccepted['car']['model']}},
                    @endif
                    @if (!empty($req->requestPurchaseAccepted['car']['colour']))
                        {{$req->requestPurchaseAccepted['car']['colour']}},
                    @endif
                    @if (!empty($req->requestPurchaseAccepted['car']['number']))
                        {{$req->requestPurchaseAccepted['car']['number']}},
                    @endif
                </td>

                <td>
                    @if (!empty($req->requestPurchaseAccepted['date_find_car']))
                        {{ date("d.m.y H:i:s", strtotime($req->requestPurchaseAccepted['date_find_car'])) }}
                    @endif
                </td>
                <td>
                    @if (!empty($req->requestPurchaseAccepted['date_answer_purchase']))
                        {{ date("d.m.y H:i:s", strtotime($req->requestPurchaseAccepted['date_answer_purchase'])) }}
                    @endif
                </td>
                <td>
                    @if (!empty($req->requestPurchaseAccepted['date_come_car_send']))
                        {{ date("d.m.y H:i:s", strtotime($req->requestPurchaseAccepted['date_come_car_send'])) }}
                    @endif
                </td>
                <td>
                    @if (!empty($req->requestPurchaseAccepted['products']))
                        @foreach($req->requestPurchaseAccepted['products'] as $product)
                            <b>{{ $product['name']  }} </b>, <i>{{ $product['pivot']['weight'] }} {{ $product['pivot']['unit'] }}</i> <br>
                        @endforeach
                    @endif
                </td>
                <td>
                    @if (!empty($req->requestPurchaseAccepted['date_answer_buh']))
                        {{ date("d.m.y H:i:s", strtotime($req->requestPurchaseAccepted['date_answer_buh'])) }}
                    @endif
                </td>
                <td>{{ $req->requestPurchaseAccepted['accountant']['name'] }}</td>
            @endif
            @if ($type == "check_delivery" || $type == "payment" || $type == "archive_complete")
                <td>
                    @if (!empty($req->requestPurchaseAccepted['date_come_car_take']))
                        {{ date("d.m.y H:i:s", strtotime($req->requestPurchaseAccepted['date_come_car_take'])) }}
                    @endif
                </td>
            @endif
            @if ($type == "archive_complete")
                <td>
                    @if (!empty($req->requestPurchaseAccepted['date_archive']))
                        {{ date("d.m.y H:i:s", strtotime($req->requestPurchaseAccepted['date_archive'])) }}
                    @endif
                </td>
            @endif
        </tr>
    @endforeach
    </tbody>
</table>
</body>
</html>

resources/views/logist/not_registry/print_sale.blade.php
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Print</title>
        <style type="text/css">
            table {
                width:100%;
                border: 1px solid black;
                border-collapse:collapse;
            }
            th {
                text-align: left; /* Выравнивание по левому краю */
                background: #D3D3D3; /* Цвет фона ячеек */
                border: 1px solid black; /* Граница вокруг ячеек */
            }
            td {
                border: 1px solid black; /* Граница вокруг ячеек */
            }
        </style>

    </head>
    <body onload="setTimeout(function () { window.print(); }, 500); window.onfocus = function () { setTimeout(function () { window.close(); }, 500); }">
        <table>
            <thead>
            <tr>
                <th>№</th>
                <th>Дата</th>
                <th>Менеджер</th>
                <th>Комментарий</th>
                <th>Точка А</th>
                <th>Точка Б</th>
                <th>Расстояние</th>
                <th>Тоннаж(кг)</th>
                <th>Тип загрузки</th>
                @if ($type == "archive")
                    <th>Цена</th>
                    <th>Комментарий</th>
                    <th>Дата ответа</th>
                    <th>Логист</th>
                @endif
            </tr>
            </thead>
            <tbody>

            @foreach ($requests as $req)
                <tr>
                    <td>{{ $req->id }}</td>
                    <td>{{ date("d.m.y H:i:s", strtotime($req->created_at)) }}</td>
                    <td>{{ $req->userCreate->name }}</td>
                    <td>{{ $req->comment_create }}</td>
                    <td>{{ $req->farmsAddressA->name }}, {{ $req->farmsAddressA->address }}</td>
                    <td>{{ $req->farmsAddressB->name }}, {{ $req->farmsAddressB->address }}</td>
                    <td>{{ $req->distance }}</td>
                    <td>{{ $req->tonnage }}</td>
                    <td>{{ $req->typeLoad->name }}</td>
                    @if ($type == "archive")
                        <td>{{ $req->price }}</td>
                        <td>{{ $req->comment }}</td>
                        <td>
                            @if (!empty($req->date_answer))
                                {{ date("d.m.y H:i:s", strtotime($req->date_answer)) }}
                            @endif
                        </td>
                        <td>
                            @if (isset($req->userLogist))
                                @if (!empty($req->userLogist->last_name))
                                    {{$req->userLogist->last_name }},
                                @endif
                                {{$req->userLogist->name}}
                            @endif
                        </td>
                    @endif
                </tr>
            @endforeach
            </tbody>
        </table>
    </body>
</html>